// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: store_file/v1/file_stored.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileStored struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FileId      *string                `protobuf:"bytes,1,opt,name=file_id,json=fileId"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt"`
	xxx_hidden_Size        int64                  `protobuf:"varint,3,opt,name=size"`
	xxx_hidden_MediaType   *string                `protobuf:"bytes,4,opt,name=media_type,json=mediaType"`
	xxx_hidden_Extension   *string                `protobuf:"bytes,5,opt,name=extension"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FileStored) Reset() {
	*x = FileStored{}
	mi := &file_store_file_v1_file_stored_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStored) ProtoMessage() {}

func (x *FileStored) ProtoReflect() protoreflect.Message {
	mi := &file_store_file_v1_file_stored_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileStored) GetFileId() string {
	if x != nil {
		if x.xxx_hidden_FileId != nil {
			return *x.xxx_hidden_FileId
		}
		return ""
	}
	return ""
}

func (x *FileStored) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *FileStored) GetSize() int64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *FileStored) GetMediaType() string {
	if x != nil {
		if x.xxx_hidden_MediaType != nil {
			return *x.xxx_hidden_MediaType
		}
		return ""
	}
	return ""
}

func (x *FileStored) GetExtension() string {
	if x != nil {
		if x.xxx_hidden_Extension != nil {
			return *x.xxx_hidden_Extension
		}
		return ""
	}
	return ""
}

func (x *FileStored) SetFileId(v string) {
	x.xxx_hidden_FileId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *FileStored) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *FileStored) SetSize(v int64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *FileStored) SetMediaType(v string) {
	x.xxx_hidden_MediaType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *FileStored) SetExtension(v string) {
	x.xxx_hidden_Extension = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *FileStored) HasFileId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FileStored) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *FileStored) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *FileStored) HasMediaType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *FileStored) HasExtension() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *FileStored) ClearFileId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FileId = nil
}

func (x *FileStored) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *FileStored) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Size = 0
}

func (x *FileStored) ClearMediaType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_MediaType = nil
}

func (x *FileStored) ClearExtension() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Extension = nil
}

type FileStored_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier for the file, format a UUID like '123e4567-e89b-12d3-a456-426614174000'
	FileId *string
	// Timestamp when the file metadata was created
	CreatedAt *timestamppb.Timestamp
	// Size of the file in bytes
	Size *int64
	// Media type of the file, e.g., "image/png", "application/pdf"
	// for download, the media type is used to set the Content-Type header
	MediaType *string
	// File extension including a dot, e.g., ".png", ".pdf"
	// For download generate a random file name and append the extension, ensures that the file name does not contains personal information or internal identifiers
	Extension *string
}

func (b0 FileStored_builder) Build() *FileStored {
	m0 := &FileStored{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FileId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_FileId = b.FileId
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Size = *b.Size
	}
	if b.MediaType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_MediaType = b.MediaType
	}
	if b.Extension != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Extension = b.Extension
	}
	return m0
}

var File_store_file_v1_file_stored_proto protoreflect.FileDescriptor

const file_store_file_v1_file_stored_proto_rawDesc = "" +
	"\n" +
	"\x1fstore_file/v1/file_stored.proto\x12\rstore_file.v1\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x01\n" +
	"\n" +
	"FileStored\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\x12\x1c\n" +
	"\textension\x18\x05 \x01(\tR\textensionB[ZQgithub.com/kinneko-de/sample-transaction-log-tailing-mongodb/golang/store_file/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_store_file_v1_file_stored_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_store_file_v1_file_stored_proto_goTypes = []any{
	(*FileStored)(nil),            // 0: store_file.v1.FileStored
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_store_file_v1_file_stored_proto_depIdxs = []int32{
	1, // 0: store_file.v1.FileStored.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_store_file_v1_file_stored_proto_init() }
func file_store_file_v1_file_stored_proto_init() {
	if File_store_file_v1_file_stored_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_file_v1_file_stored_proto_rawDesc), len(file_store_file_v1_file_stored_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_file_v1_file_stored_proto_goTypes,
		DependencyIndexes: file_store_file_v1_file_stored_proto_depIdxs,
		MessageInfos:      file_store_file_v1_file_stored_proto_msgTypes,
	}.Build()
	File_store_file_v1_file_stored_proto = out.File
	file_store_file_v1_file_stored_proto_goTypes = nil
	file_store_file_v1_file_stored_proto_depIdxs = nil
}
